apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogservice
  labels:
    app: catalogservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogservice
  template:
    metadata:
      labels:
        app: catalogservice
    spec:
      containers:
        - name: catalogservice
          image: eshopregistry.azurecr.io/catalogservice:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: catalogservice-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: catalogservice
